## Artificial Neural Network Classifier


In [1]:
import numpy as np

Creating arrays for the data

In [2]:
# a third column is added for multiplying in x0
x = np.array(([30, 50, 1], [60, 80, 1], [20, 30, 1]), dtype=float)
y = np.array(([85], [95], [75]), dtype=float)

# normalizing data
x = x / (np.sqrt((np.sum(x**2))))
y = y / (np.sqrt((np.sum(y**2))))

Generating random weights

In [3]:
w1 = np.random.randn(3, 4) # 3 inputs to 4 neurons of hidden layer
w2 = np.random.randn(4, 1) # 4 neurons to 1 output 

Creating sigmoid and derivative of sigmoid functions

In [4]:
def sigmoid(f):
        return 1/(1 + np.exp(-f))
    
def dSigmoid(f): # change it to dSigmoid
    return sigmoid(f) * (1 - sigmoid(f))

Using the FEED-FORWARD algorithm

In [5]:
R = x.dot(w1)
H = sigmoid(R)
S = H.dot(w2)
yhat = sigmoid(S)

Create a copy of the weights used for updating without changing the original

In [6]:
G1 = np.copy(w1)
G2 = np.copy(w2)

3 epoch for updating weights

In [7]:
for i in range(3):
    print("Iteration number ", i)
    
    R = x.dot(G1)
    H = sigmoid(R)
    S = H.dot(G2)
    yhat = sigmoid(S)
    
    B2 = (y - yhat) * dSigmoid(S)
    G2 = H.T.dot(B2) 
    B1 = B2.dot(w2.T) * dSigmoid(R)
    G1 = x.T.dot( B1 )
    
    print("Input to Hidden: \n", R)
    print("Weight 1:\n", w1)
    print("New weight: \n", G1)
    
    print("Output of Hidden: \n", H)
    print("Weight 2:\n", w2)
    print("New weight: \n", G2, "\n-------\n")
    

Iteration number  0
Input to Hidden: 
 [[-0.06428162  0.52253271  0.35232951 -0.32541091]
 [-0.13772549  0.89161304  0.58054636 -0.55868863]
 [-0.05148331  0.32271475  0.21860655 -0.20033841]]
Weight 1:
 [[-0.43851333  0.56063395  0.22337299 -0.36917561]
 [ 0.14166314  0.93113863  0.69904855 -0.57370129]
 [-1.72228429 -0.01576142  1.0684239   0.30233161]]
New weight: 
 [[-1.30923419e-02  6.27399197e-04 -1.45953740e-02 -1.44473692e-02]
 [-1.88981393e-02  9.10866663e-04 -2.11165818e-02 -2.09006644e-02]
 [-3.38532408e-04  1.67413319e-05 -3.82281409e-04 -3.78142875e-04]]
Output of Hidden: 
 [[0.48393513 0.62773981 0.58718236 0.41935764]
 [0.46562295 0.70922293 0.64119311 0.36385094]
 [0.48713201 0.57998572 0.55443503 0.45008224]]
Weight 2:
 [[-1.50863489]
 [ 0.08235935]
 [-1.77804727]
 [-1.75121042]]
New weight: 
 [[0.05212441]
 [0.07042314]
 [0.06531037]
 [0.04437145]] 
-------

Iteration number  1
Input to Hidden: 
 [[-0.01103464  0.00053096 -0.01232165 -0.01219596]
 [-0.01894943  0.0009

Testing using resulted weights

In [8]:
testing = np.array(([50, 20, 1], [40, 70, 1], [40, 60, 1]), float)

R = x.dot(G1)
H = sigmoid(R)
S = H.dot(G2)
yhat = sigmoid(S)
print(yhat)



[[0.51234049]
 [0.51231711]
 [0.51235283]]


-